CREATE TABLE `Coin` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`coin`	INTEGER NOT NULL
);

CREATE TABLE `Soda` (
    `id`    INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    -- `soda_type_id` INTEGER NOT NULL,
    `cost`    INTEGER NOT NULL
);

INSERT INTO `Coin` VALUES (null, 1);
INSERT INTO `Coin` VALUES (null, 1);


INSERT INTO `Soda` VALUES (null, 2);
INSERT INTO `Soda` VALUES (null, 2);
INSERT INTO `Soda` VALUES (null, 2);
INSERT INTO `Soda` VALUES (null, 2);
INSERT INTO `Soda` VALUES (null, 2);
INSERT INTO `Soda` VALUES (null, 2);
INSERT INTO `Soda` VALUES (null, 2);
INSERT INTO `Soda` VALUES (null, 2);
INSERT INTO `Soda` VALUES (null, 2);
INSERT INTO `Soda` VALUES (null, 2);
INSERT INTO `Soda` VALUES (null, 2);
INSERT INTO `Soda` VALUES (null, 2);
INSERT INTO `Soda` VALUES (null, 2);
INSERT INTO `Soda` VALUES (null, 2);
INSERT INTO `Soda` VALUES (null, 2);
